### PR TITLE
Fix regex match on $trigger_function_name$

### PR DESCRIPTION
**Pull request by adriangb**
https://regex101.com/r/lbXoUf/1

Eg: https://www.postgresql.org/docs/13/plpgsql-trigger.html

Might also be interesting to explore https://github.com/nackjicholson/aiosql or something which I think takes care of this

### CODE REVIEW

**Comment by RonquilloAeon** [comment]
Oops you marked this PR as draft and I switched it back. Let me know when you're ready for me to review.

https://github.com/nackjicholson/aiosql looks like a good solution for not having to manually deal w/ queries, at least for Postgres.

**Comment by adriangb** [comment]
Ready for review, but I switched it to a draft because I wanted to make sure this was tested / discussed before merging! I'm not sure this works well / regexing this stuff is hard.

**Comment by RonquilloAeon** [comment]
100%! It'd be great if you could create some parameterized tests for `Query` to verify that your regex change works as well as ensuring that we don't have any regressions.

**Comment by adriangb** [comment]
Sounds good, I haven't fully grasped the testing setup yet though, I assume I spin up the docker compose and then just run `pytest`? It might help to have tests in CI (if possible)

**Comment by RonquilloAeon** [comment]
Yes, `docker compose up` and then you can run `nox`. I use pyenv on my machine to allow nox to test different versions of python.

There is a test workflow but it didn't run when you submitted a PR, so that's something to look at.

As for testing your regex change, it should be as simple as updating the cases in this file. I had forgotten that these existed:
https://github.com/RonquilloAeon/migri/blob/master/test/asyncpg/test_postgresql.py

**Comment by RonquilloAeon** [comment]
@adriangb the way you get the multi-version tests to work is:
- install pyenv
- Install python for 3.7, 3.8, 3.9
- In each version of python that migri supports, install nox
- Create a `.python-version` file in project root with the Python version. For example:
```
3.7.5
3.8.7
3.9.1
3.10.2
```
- Run `nox`

**Comment by adriangb** [comment]
I'll give it a shot!

**Comment by RonquilloAeon** [comment]
@adriangb I published a new version of migri. They include your recent PR changes (click version bump and support for instantiated connections). When this PR is merged, I'll release a bugfix version.

I appreciate all your help!

**Comment by adriangb** [comment]
I got the tests working, thank you for guiding me.

However my first attempt at a regex failed, it's using negative lookaheads and... yeah maybe I'm just bad at regex. But maybe it's worth taking a step back: what is the goal of this parsing? It doesn't make much sense to me to have parameters in a migration statement. Is it just for Migri's internal use?

**Comment by RonquilloAeon** [comment]
Good news re: testing! I believe my original intention for that parser was to create a single parameter format (since the replacement format is different across databases). I can't recall if I had a specific use case in mind when I created it. Because you're right that migrations usually don't need parameters. Maybe I meant it for scripted migrations.

Short term, if you need function name parameters to work, I can help you with the regex. I suggest we open a separate issue to assess if the Query class can go. We can also see if there's another library that handles substitutions thoroughly.

**Comment by adriangb** [comment]
I was able to fix my issue short-term by using:

```sql
CREATE FUNCTION trigger_func() RETURNS trigger AS $$
```

Instead of:

```sql
CREATE FUNCTION trigger_func() RETURNS trigger AS $trigger_func$
```

So really I just want to think though what would be the best solution for the codebase long term.

> my original intention for that parser was to create a single parameter format (since the replacement format is different across databases)

I feel makes sense, but at the same time I expect that migrations for different databases are going to have other differences, e.g. UUID columns, constraints, etc. So I think if users were switching from one database to another they'd likely have to make changes to their migrations anyway, so using the same parameters everywhere would be of little benefit. Besides, like you said above it doesn't make much sense to have parameters in migrations in the first place.

Looking through the codebase, I do see that the parameters to `Query` are used to record / look up the migrations themselves, for example:

https://github.com/RonquilloAeon/migri/blob/691713c8f3efbfc433a339072fba66f0b8c163de/migri/migration.py#L222-L226

So I wonder if the solution here might be to remove `Query` from the processing of the _user's_ migration statements and only keep it for migri itself? Then maybe get rid of `Query` altogether to simplify the codebase and instead just hardcode their logic into each backend since there is already an abstraction over each backend.

**Comment by RonquilloAeon** [comment]
I checked out Xpresso, your framework, in more detail. Very cool! I'm going to play with it soon. It's the perfect use case for `migri`. When I started using FastAPI, I missed the simplicity of Django's migration system. Alembic is bleh and overkill for my taste. Of course, Django does a lot more than run migrations, but small projects don't need all that Django migrations/alembic offer.

So my vision for `migri` is to create a simple migration system that works with different relational databases. I'm not so much interested in facilitating the use case of switching databases (e.g. from Mysql to Postgres) in a mature codebase. That rarely happens anyway. I want one common interface. Sometimes I use SQLite and sometimes Postgres. Regardless of my project, I want to spend more time coding than dealing with the specific connection/setup/migration quirks of each database.

Of course, each database has its own differences but generally, those differences are contained to the DSL or can be abstracted away w/ the `ConnectionBackend`.

I wrote `Query` specifically to protect against SQL injections. Sometimes in migrations, you need to iterate over a CSV or JSON file in Python. So while it's not input that's directly from an outside actor, it's still an attack vector.

As I wrote out that last paragraph, I realized that even loading data from a file isn't a common thing w/ migrations. I think I over-engineered. Let me think a bit on this, but currently, I'm leaning towards your suggestion of slowly plucking out `Query`.

**Comment by RonquilloAeon** [comment]
I created a new issue:
https://github.com/RonquilloAeon/migri/issues/61

**Comment by adriangb** [comment]
Sounds good, I'm going to close this for now since I think I solved the issue short term, I'll re-open if that changes

**Comment by adriangb** [comment]
Thanks for the kind words about Xpresso! It's still very much in development, so if you have experience with FastAPI and Django your input on the APIs / features / etc. would be much appreciated.

> So my vision for migri is to create a simple migration system that works with different relational databases.

Yep +1 I like the idea. I think having 1 lib handle them all with some common interfaces (like the `ConnectionBackend` abstraction) makes sense. But I'm not so sure that trying to make the SQL for each DB match up makes much sense, I think if you're writing migrations for Postgres the SQL is going to be Postgres specific anyway.

> Sometimes in migrations, you need to iterate over a CSV or JSON file in Python

Interesting, I guess that makes sense if you need to backfill data or something. I hadn't thought of that. But yeah it does seem like a more niche use case. I think what I might do is wait until there is more user feedback and then implement the feature with a more thorough understanding of use cases? (that's just my thoughts though, it's your lib 😄 )

**Comment by RonquilloAeon** [comment]
100%! I'm going to spend time this weekend playing w/ Xpresso so I can get a feel for it and see how I can help you!

After giving this more thought, I agree with you. I made a mistake on this part of the design by taking a niche use case into consideration while designing a core piece of migri.

I appreciate your input! It's been mostly me and my use cases up to this point. Your feedback is invaluable.

**Pull request closed without merging**
